# Generated by Django 6.0.7 on 2026-07-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_scrapedjob_resumeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysishistory',
            name='analysis_type',
            field=models.CharField(choices=[('ATS', 'ATS'), ('AI_ANALYSIS', 'AI Analysis'), ('JOB_MATCH', 'Job Match'), ('COVER_LETTER', 'Cover Letter'), ('INTERVIEW', 'Interview Questions'), ('REWRITE', 'Rewritten Resume')], max_length=30),
        ),
    ]
