# Generated by Django 6.0.7 on 2026-07-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_alter_analysishistory_analysis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysishistory',
            name='analysis_type',
            field=models.CharField(choices=[('ATS', 'ATS'), ('AI_ANALYSIS', 'AI Analysis'), ('JOB_MATCH', 'Job Match'), ('COVER_LETTER', 'Cover Letter'), ('INTERVIEW', 'Interview Questions'), ('REWRITE', 'Rewritten Resume'), ('UNIFIED_ANALYSIS', 'Unified Analysis')], max_length=50),
        ),
    ]
