# Generated by Django 6.0.7 on 2026-08-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_alter_analysishistory_analysis_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedJob',
        ),
    ]
